### ISSUE TITLE
sjt.lmer() print variance for random slope

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#328] opened 2018-01-26 10:26 UTC
Currently `sjt.lmer()` prints only the random intercept variance.
Is it possible to add also the random slope variance?
```
m <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)
sjt.lmer(m, show.est = T, show.std = T, show.ci = T, show.se = T, show.header = T,
         show.col.header = T, show.r2 = T, show.icc = T, show.re.var = T, 
         show.fstat = T, show.aic = T, show.aicc = T, show.dev = T)
summary(m)
Random effects:
 Groups   Name        Variance Std.Dev. Corr
 Subject  (Intercept) 612.09   24.740       
          Days         **35.07**    5.922   0.07
 Residual             654.94   25.592       
Number of obs: 180, groups:  Subject, 18
```

**Comment by strengejacke** [comment] 2018-01-26 12:37
Duplicate of #279 
Revision of table-output-functions (`sjt.`) is planned for the next major release, scheduled in about 1-2 months.

**Closed by strengejacke** 2018-01-26 12:37 UTC
