### ISSUE TITLE
Feature Request: Interaction Plots for Models with Clustered Standard Errors

### ISSUE THREAD

**Issue by DeFilippis** [strengejacke/sjPlot#444] opened 2018-12-13 20:43 UTC
Huge fan of this package, but unfortunately, most of my work involves models with clustered standard errors, e.g. `felm` in the `lfe` package or `lm_robust` in the `estimatr` package.  Is there a way to spit out interaction plots for these models using your package?

**Comment by strengejacke** [comment] 2018-12-13 21:08
Do you want to plot estimates or marginal effects?

**Comment by DeFilippis** [comment] 2018-12-13 21:19
Both if possible, but marginal effects are more pressing.

**Comment by strengejacke** [comment] 2018-12-13 21:45
At least `lmRob` is supported by *ggeffects*, but I can take a look at the `lm_robust` function.

**Comment by strengejacke** [comment] 2018-12-14 08:05
_Should_ be fixed now, after updating **sjstats** and **ggeffects** from CRAN. Marginal effects, `tab_model()` and `plot_model()` should work for felm and lm_robust, though it's not possible to get marginal effects from felm-objects (due to missing predict method).

**Comment by DeFilippis** [comment] 2018-12-14 15:07
Wow.  You're incredible.  That was such fast turn around.  Thanks so much!

**Comment by DeFilippis** [comment] 2018-12-17 17:50
@strengejacke , I'm still getting the same error:

`Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "lm_robust"`

Thoughts?

**Comment by DeFilippis** [comment] 2018-12-17 18:01
Problem above resolved today when I re-installed everything via githubinstall

**Comment by DeFilippis** [comment] 2018-12-17 18:11
@strengejacke , I'm still getting the same error:

Error in UseMethod("family") : no applicable method for 'family' applied to an object of class "lm_robust"

Thoughts?

**Comment by strengejacke** [comment] 2018-12-17 21:18
Yes, you also need to install sjstats from GitHub, I think.

**Comment by DeFilippis** [comment] 2018-12-17 21:30
@strengejacke 

I re-installed ggeffects, sjstats, and sjplot from GitHub, and it is still throwing the same error:

```
mod <- lm_robust(outcome ~ politics + treatment  + politics:treatment,
  data =  data,
  clusters = team,
  se = "stata"
)

plot_model(mod, type = "int")
```

> 
> Error in UseMethod("family") : 
>   no applicable method for 'family' applied to an object of class "lm_robust"

**Comment by strengejacke** [comment] 2018-12-18 07:58
Are you sure you have installed the most recent version from GitHub? For me, everything works as intended:

``` r
library(sjPlot)
#> Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!
library(estimatr)
library(fabricatr)
dat <- fabricate(
  N = 40,
  y = rpois(N, lambda = 4),
  x = rnorm(N),
  z = rbinom(N, 1, prob = 0.4)
)

lmro <- lm_robust(y ~ x * z, data = dat)
plot_model(lmro, type = "int")
```

![](https://i.imgur.com/HqCR5n6.png)

**Comment by DeFilippis** [comment] 2018-12-18 17:10
Thank you so much for taking the time.  The problem seemed to be caused by `devtools::install_github("strengejacke/strengejacke")` seemed to do the trick, whereas using `githubinstall:githubinstall()` did not.  Thanks a bunch!

**Comment by strengejacke** [comment] 2018-12-18 18:23
Ok, I updated the readme... strange, though.

**Closed by strengejacke** 2018-12-18 18:23 UTC

**Comment by lukesonnet** [comment] 2018-12-21 16:47
Thanks for supporting `lm_robust`!

**Comment by daveholtz** [comment] 2019-07-24 18:56
@strengejacke thank you so much for this package! really amazing. I'm a bit confused by one of your previous responses in this thread:

```
Should be fixed now, after updating sjstats and ggeffects from CRAN. Marginal effects, tab_model() and plot_model() should work for felm and lm_robust, though it's not possible to get marginal effects from felm-objects (due to missing predict method).
```

Does any of this functionality work given the lack of predict method for felm objects? I note you say that Marginal effects, tab_model(), and plot_model() should work for felm, but that doesn't seem to be the case...thanks!

**Comment by strengejacke** [comment] 2019-07-24 20:00
Do you have a reprex? For me, `plot_model()` and `tab_model()` work with `felm`-objects.

**Comment by daveholtz** [comment] 2019-07-24 20:05
```
> library(sjPlot)
> library(sjmisc)

Attaching package: ‘sjmisc’

The following object is masked from ‘package:tidyr’:

    replace_na

> library(ggplot2)
> data(efc)
> theme_set(theme_sjplot())
> efc$c161sex <- to_factor(efc$c161sex)
> 
> # fit model with interaction
> fit <- felm(neg_c_7 ~ c12hour + barthtot * c161sex, data = efc)
> plot_model(fit, type = "pred", terms = c("barthtot", "c161sex"))
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "felm"
```

**Comment by strengejacke** [comment] 2019-07-24 20:38
Yes, marginal effects plots still don't work, but plotting estimates (or `tab_model()`) does.

**Comment by daveholtz** [comment] 2019-08-03 18:18
Ah whoops, I had misunderstood your previous comment(s). Got it, sorry for the confusion, and thank you for taking the time to respond!
