### ISSUE TITLE
sjt.glmer() not printing out multiple random effects correlation

### ISSUE THREAD

**Issue by DikobrazDante** [strengejacke/sjPlot#251] opened 2017-06-25 10:33 UTC
Hello everybody!

When we have a model like `y ~ x + (1+x|A) + (1+x|B)` I have noticed that in the summary table the correlation between intercept and slope for random effects (RE) in A is being printed out as ro1, but there is no ro2 for the RE correlation in B. Am I missing something here or is this an error?
![image](https://user-images.githubusercontent.com/28704152/27515405-82f7e178-59a2-11e7-9242-4cad8acc715b.png)

**Comment by DikobrazDante** [comment] 2017-06-25 20:40
I know it's a bad example, but is still shows the problem.

    library(tidyverse)
    library(sjPlot)
    library(lmerTest)
    library(sjmisc)
    data(efc)
    efc$e15relat <- factor(efc$e15relat)
    efc$e42dep <- factor(efc$e42dep)
    efc$Rand <- sample(x = c(0,1), size = nrow(efc), replace = T)
    fit1 <- glmer(Rand ~ c12hour + (1+c12hour | e15relat) + (1+c12hour|e42dep), data = efc, family = "binomial")
    sjt.glmer(fit1)

Only rho1 is shown...

**Comment by strengejacke** [comment] 2017-06-29 21:23
I think I need to revise the table output of the random parts to address this issue.

**Comment by strengejacke** [comment] 2018-01-18 21:34
Possible duplicate of https://github.com/strengejacke/sjPlot/issues/279, so I'll close this one.

**Closed by strengejacke** 2018-01-18 21:34 UTC
