### ISSUE TITLE
support for survey/srvyr package

### ISSUE THREAD

**Issue by paulb20** [strengejacke/sjPlot#189] opened 2017-01-11 11:05 UTC
As a user of social surveys which have weights to population totals, I use the survey package a lot. Do like the sjPlot/sjmisc packages, but it looks as though the [srvyr package](https://github.com/gergness/srvyr)  to use dplyr-like functions is going in slightly different directions. Any chance of bringing these together?

**Comment by sjPlot** [comment] 2017-01-11 11:39
Could you give an example of what you exactly mean? I'm not quite sure what kind of changes you suggest for the sjPlot or sjmisc-packages: More functions, different syntax, support for other models?

**Comment by paulb20** [comment] 2017-01-11 15:30
Basically, sj(p/t).frq has a weights function (also sjmisc::frq). What I'd like, for surveys with weights, is for a default to display confidence intervals (or SE), and showCI to be default. 

These would use the methods from survey package which (afaik) is the standard for complex surveys in R. 

Equally, I regularly use survey::svytable to get weighted crosstabs, plotted as dotplots or dodged bars. Again, it'd be good to use survey to get confidence intervals for plotting in that case.

The further complication is the survey modelling functions such as svyglm.

srvyr has some ways of getting at this, but I find myself going back to survey package as many of the social surveys I use are mostly categorical variables, with sometimes the only numeric being the weight variable, and the dplyr-ish summarize functions only work with numerics which are less easy to present to users when categorical variables are easily understood (e.g. In work or not, ethnic groups, and the crosstab of both)

**Comment by sjPlot** [comment] 2017-01-11 21:40
Ok, I understand. So you're would like to see support for the survey-package in sjPlot. This might be a task for my next plans - extracting the core of data tyding from sjPlot into a separate package, so you get the "ready to plot" data and can build your own ggplot-objects. Once I have a function that returns a generic data frame, independent from the type of model given, I can easily integrate / support more and more object classes, which also addresses [this](https://github.com/sjPlot/devel/issues/156) and [this](https://github.com/sjPlot/devel/issues/131) issue.

**Comment by methodds** [comment] 2017-03-01 13:32
Related to that: It would be awesome if sjPlot could also support the survey weighted version for t-tests, ``svyttest``.

**Comment by sjPlot** [comment] 2017-03-01 13:38
So, is a t-test worth the effort? ;-)

**Comment by methodds** [comment] 2017-03-01 13:43
This is actually a reasonable question. I've been discussing this with colleagues a lot, as we always come to the conclusion that researchers never use t-tests anyway but directly regressions etc. 
However, we also agree that t-test are the easiest example for introducing students two simple inference measures, why is why we teach them anyway. 
If you have any better suggestions, it'd be more than happy to try it =)

**Comment by sjPlot** [comment] 2017-03-01 13:49
No, I'm not putting the t-test into question - I was wondering if the numbers to report are such overwhelming that it's worth writing a plotting/table function for it?

**Comment by methodds** [comment] 2017-03-01 13:58
Ah I see. Hm no they are not overwhelming at all, I think that they numbers in R are even underwhelming. This is the output of a paired t-test in Stata:
![image](https://cloud.githubusercontent.com/assets/7460499/23462626/de23e1a6-fe8e-11e6-99a9-6d89db65ba49.png)
It includes everything that is of interest (group specific and difference wise), means, standard deviations, confidence intervals, nr. of observations, df's, p values.
In comparison this is the t-test in R:
![image](https://cloud.githubusercontent.com/assets/7460499/23462698/1e187c7c-fe8f-11e6-9000-f481d105c0ab.png)

There is much less information, which I dislike. I think if one would want all the infos from the Stata output, then a table function is worth it.

**Comment by sjPlot** [comment] 2017-03-01 14:27
`sjt.ttest` sounds/looks like `titel, thesen, temperamente` ;-)

I see your point, and this would be a new issue for implementing table output of t-tests (in general and from survey package).

**Comment by methodds** [comment] 2017-03-01 14:30
I'll take the liberty to open a new issue =)

**Comment by strengejacke** [comment] 2017-09-19 19:30
survey-regression-models already work with `plot_model()`. The revision of frequency and cross tables is planned for a forthcoming update, but not the next one.

**Comment by strengejacke** [comment] 2024-09-24 12:22
> I think there is too little information to achieve this.

Closing now, not sure this will be addressed soon, unless someone want to submit a PR.

**Closed by strengejacke** 2024-09-24 12:22 UTC
Labels: enhancement
