### ISSUE TITLE
plot_model(..., type = "re") not working for lmer-models including '||' notation

### ISSUE THREAD

**Issue by henningsway** [strengejacke/sjPlot#676] opened 2020-08-13 10:53 UTC
``` r
library(lme4)
#> Loading required package: Matrix
library(sjPlot)
m1 <- lmer(Reaction ~ Days + (Days || Subject), data = sleepstudy)
plot_model(m1, type = "re")
#> Error in array(NA, c(J, K)): 'dims' cannot be of length 0
```

<sup>Created on 2020-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment] 2020-08-13 11:04
Possible duplicate of https://github.com/easystats/parameters/issues/202 and https://github.com/strengejacke/sjPlot/issues/604. Closing in favor of parameters-202.

**Closed by strengejacke** 2020-08-13 11:04 UTC
