### ISSUE TITLE
tab_model() lmer "Error: Column 6 must be named"

### ISSUE THREAD

**Issue by abaimel** [strengejacke/sjPlot#392] opened 2018-08-01 22:07 UTC
Hi again,

The tab_model() call for _lmer_ models is producing the following error message: "Error: Column 6 must be named" - verified on different data sets, with different random effect structures, and the error is persistent.

Running a _glmer_ model with the same random effect structure works as expected.

Cheers!

**Comment by strengejacke** [comment] 2018-08-02 05:46
Possible duplicate of https://github.com/strengejacke/sjPlot/issues/388

Please use `lme4:: lmer()` to fit the model.

**Closed by strengejacke** 2018-08-02 05:46 UTC

**Comment by strengejacke** [comment] 2018-08-02 10:00
I added a workaround (i.e. an own tidier) for lmerModLmerTest-Objects, so this issue should be fixed in sjPlot now. Will commit tonight.

**Comment by abaimel** [comment] 2018-08-02 16:18
Awesome! Thanks again for the speedy responses - really appreciated. The problem was indeed lmerTest related. Cheers.

**Comment by yanyidi** [comment] 2019-05-02 13:32
Hi there,
`lme4::lmer()` solves the problem but `lmerTest::lmer()` doesn't. However, the first one doesn't come with the p-value. How can I get p-value then? Thanks!

**Comment by strengejacke** [comment] 2019-05-02 14:10
`tab_model()` automatically prints p-values, else use `sjstats::p_value()`.

**Comment by yanyidi** [comment] 2019-05-02 14:23
> `tab_model()` automatically prints p-values, else use `sjstats::p_value()`.

Thanks for the prompt reply.
The table is so nice!!!

**Comment by yanyidi** [comment] 2019-05-02 14:29
But 
`fit <- lme4::lmer(age ~ weight + length + (1 | id), data = dat, na.action="na.omit", REML=T)
tab_model(fit)`
appears another issue: "Computing p-values via Wald-statistics approximation (treating t as Wald z)."

`lmerTest` works fine. But `lmerTest` has that "Error: Column 6 must be named" again.
