### ISSUE TITLE
Splitting glmmTMB models into conditional and zero-inflated not working

### ISSUE THREAD

**Issue by riddhimn** [strengejacke/sjPlot#685] opened 2020-09-18 00:42 UTC
Hi strengejacke -- I'm using your your excellent sjPlot package to make forest plots of zero-inflated beta regression model using glmmTMB. I'd like to present two plots for each of the models, one conditional and one zero-inflated (as suggested [here](https://github.com/strengejacke/sjPlot/issues/414)). But when I run the plot_model code, I only get one plot (see below) with one the first model results presented (both conditional and zero-inflated) on one plot, even though grid = T. Also, for some of the coefficients, there is only one color present, although there are two dots visible. Would you have some suggestions for how to fix this? 

```
plot_model(zoib.bc.gov.union, zoib.bc.gov,
           type = "est", 
           transform = NULL,
           grid = TRUE,
           terms = c("Pct.Appointed","Pct.Participant.Elected", "Pct.Appointed:gov.controlDem", "Pct.Participant.Elected:gov.controlDem", "Pct.Appointed:union.binary1", "Pct.Participant.Elected:union.binary1", "Pct.Appointed:gov.controlDem:union.binary1", "Pct.Participant.Elected:gov.controlDem:union.binary1"),
           show.values = T, 
           value.offset = 0.3)
```

![zoib_plot](https://user-images.githubusercontent.com/12899611/93542122-13c83380-f90d-11ea-8b4a-d6609a1a4304.JPG)

**Comment by strengejacke** [comment] 2020-09-18 11:02
Yes, that's a bug introduced by the latest [parameters](https://cran.r-project.org/package=parameters) update. The issue is fixed, maybe I'll try to submit an update shortly, due to the "severeness" of that bug.

You can try updating parameters from GitHib (see here: https://github.com/easystats/parameters) and check if it works...

**Comment by riddhimn** [comment] 2020-09-18 17:51
Thanks for the tip. I updated parameters via Github. And it appears to work, in part. Is there a way to ensure that the interaction effects are shown on either the conditional or zero-inflated plots, rather than in a plot of their own? Also, the colors of the dots and confidence intervals appear to alternate between conditional and zero-inflated, which makes visually comparing the effects across the two plots somewhat confusing. Is there a way to ensure that the conditional effects (dots and CIs) are all in one color and the zero-inflated effects (dots and CIs) are in another color? Thank you so much!


```
plot_model(zoib.hurdle.bc.gov.union,
           type = "est", 
           transform = NULL,
           grid = TRUE,
           terms = c("Pct.Appointed","Pct.Participant.Elected", "Pct.Appointed:gov.controlDem", "Pct.Participant.Elected:gov.controlDem", "Pct.Appointed:union.binary1", "Pct.Participant.Elected:union.binary1", "Pct.Appointed:gov.controlDem:union.binary1", "Pct.Participant.Elected:gov.controlDem:union.binary1"),
           #axis.lim = c(0.7, 1.5), 
           show.values = T, 
           value.offset = 0.3)
```

![zoib_plot_grid](https://user-images.githubusercontent.com/12899611/93629242-cb585680-f99c-11ea-9dff-3894aaab5f04.JPG)

**Comment by strengejacke** [comment] 2020-09-18 18:36
Yes, sorry, there was still an issue with the correct component assignment. This should be fixed now, so please try to update from GitHub again.

**Comment by riddhimn** [comment] 2020-09-18 21:36
It worked! Thank you! 
![zoib_plot_grid](https://user-images.githubusercontent.com/12899611/93647025-48df8f00-f9bc-11ea-9173-fb440e57fce2.JPG)

**Closed** 2020-09-22 06:28 UTC

**Comment by Subidghimire** [comment] 2022-11-22 15:51
Thanks for this discussion guys. It is very helpful. I am working on zero-inflated negative binomial model and I am having some issues making the forest plots. I have around 60 explanatory variables in my models including three way interactions between three categorical predictors. I only want to show the forest plot for interaction terms but when I use _terms = c("CategoryCRES","area","Year")_ within the plot_model code, I run into errors.

![image](https://user-images.githubusercontent.com/118399762/203359359-769619e1-602d-4dd3-8fb5-3176a035ef27.png)

Can someone please point out I am doing wrong and how I could proceed further?

**Comment by Subidghimire** [comment] 2022-11-22 15:53
If I estimate a ZINB model with only interaction terms and try to plot the figure, it works. It looks something like this but I want the results for the full model. Any help would be really appreciated.
![image](https://user-images.githubusercontent.com/118399762/203359987-fefaa451-23c7-480b-9f99-e11c159f5cbc.png)

**Comment by Subidghimire** [comment] 2022-11-22 15:55
If I estimate the ZINB model with only interaction elements and attempt to make a forest plot it works and looks something like this. 
Is this an issue with the terms = c("") code?
I would appreciate any help on this regards.

![image](https://user-images.githubusercontent.com/118399762/203360556-0b945761-2473-4ef7-9fee-199fd1f18544.png)
