### ISSUE TITLE
Error ci_style with typre="pred" for ggeffects version 1.3.2

### ISSUE THREAD

**Issue by benjaminschlegel** [strengejacke/sjPlot#921] opened 2023-10-25 12:00 UTC
Hi Daniel

ggeffects:::plot.ggalleffects() which is called with graphics::plot() changed it's parameter names form "."-style to "_"-style with the newest version 1.3.2. Therefore ci.style is now called ci_style (as well as other name changes. Therefore plot_model raises an error when used with type="pred" with arg.match ci_style.

Best,
Benjamin

**Comment by strengejacke** [comment] 2023-10-25 12:26
Yes, it seems that I forgot to keep the old argument names for that method, and only tested for the other `plot()` methods...

**Comment by IsmetOzzer** [comment] 2023-11-07 11:13
Hi, has this issue been resolved by any chance? I am having the exact issue (which I didn't have last week, strange..)

**Comment by strengejacke** [comment] 2023-11-07 12:55
Do you have a reproducible example? After updating _ggeffects_ on CRAN, everything in _sjPlot_ is still ok (https://cran.r-project.org/web/checks/check_results_sjPlot.html). Which particular example fails?

**Comment by benjaminschlegel** [comment] 2023-11-07 13:15
Here is an example. Before I run it I updated ggeffects and sjPlot:

```
m = lm(lr_self ~ age + gender, data = glm.predict::selects2015)
sjPlot::plot_model(m, type = "pred")
```

I get the following error message:

Error in match.arg(ci_style) : 
  'arg' muss NULL oder ein Zeichenkettenvektor sein

**Comment by IsmetOzzer** [comment] 2023-11-07 15:03
I did updated the GitHub version of both ggeffects and sjPlot but no luck. 

Basically, the problem is with the "pred" part.
`sjPlot::plot_model(
  lm(mpg ~ cyl, data = mtcars),
  type = "pred", show.data = T)`
  
Error in match.arg(ci_style) : 'arg' must be NULL or a character vector

**Comment by strengejacke** [comment] 2023-11-23 22:21
Thanks, should work after updating both _sjPlot_ and _ggeffects_ from GitHub:

``` r
sjPlot::plot_model(lm(mpg ~ cyl, data = mtcars), type = "pred", show.data = T)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/E8upKVe.png)

<sup>Created on 2023-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed** 2023-11-23 22:21 UTC
Labels: bug
