### ISSUE TITLE
Problem with confidence intervals and boolean coding

### ISSUE THREAD

**Issue by wsbrum** [strengejacke/sjPlot#715] opened 2020-12-11 20:14 UTC
Hi!

I'm using the sjPlot to create some plots for a longitudinal mixed-effects model analysis. When plotting my lme4::lmer, sometime I got the error:

```
lmer(y ~ group*time_bl + poly(covariate_x, 2, raw = T)  + covariates + (1 + time_bl | patient_id))

Error: Confidence intervals could not be computed.
Warning messages:
1: Some model terms could not be found in model data. You probably need to load the data into the environment. 
2: Some model terms could not be found in model data. You probably need to load the data into the environment. 
```

I'm a new user, so I did 3h of very stupid debugging and could find out the problem apparently had to do with insight::get_data(). Later, a friend help me with the inception debug() thing and we managed to find out the problem was inside ggpredict() -> ggpredict_helper() -> insight::get_data() -> get_data.merMod() -> .prepare_get_data(). Line 118 of the latter function:

```
pv <- tryCatch({
      find_predictors(x, effects = effects, flatten = TRUE)
    }
```
Let's say my model had `n` predictors. `find_predictors` was yielding `n + 1`. Turns out it was interpreting `T`, from the polynomial regression term, as a predictor and f***ing up the whole plot. I'm a newbie as you notice in the way I reported this, but I know when coding boolean values `= TRUE` should work the same as `= T`. 

Setting `poly(covariate_x, 2, raw = T)` to `poly(covariate_x, 2, raw = TRUE)` solved it.

So I guess this is more an insight package issue maybe? Sorry if it is, but just posting here cause it could happen to others. Thanks Daniel, sjPlot is awesome, will use it in my paper.

**Comment by strengejacke** [comment] 2020-12-15 10:53
Thanks for the debugging, I think it might even be a problem of R itself:

``` r
m1 <- lm(Sepal.Length ~ poly(Sepal.Width, 2, raw = TRUE) + Petal.Length, data = iris)
m2 <- lm(Sepal.Length ~ poly(Sepal.Width, 2, raw = T) + Petal.Length, data = iris)

all.vars(formula(m1))
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length"
all.vars(formula(m2))
#> [1] "Sepal.Length" "Sepal.Width"  "T"            "Petal.Length"
```

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll look into this.

**Comment by strengejacke** [comment] 2020-12-15 12:31
From the help `?TRUE`: 

> TRUE and FALSE are reserved words denoting logical constants in the R language, whereas T and F are global variables whose initial values set to these.

So `T` and `F` are no reserved words, thus the failure with `all.vars()`. In either way, closing this issue as invalid.

**Closed by strengejacke** 2020-12-15 12:31 UTC
Labels: bug, invalid

**Comment by strengejacke** [comment] 2020-12-15 13:56
Just a short info from the R developers:

> all.vars says it returns "a character vector containing all the names which occur in an expression or call."  "T" is a name.

So everything seems to be "consistent" and "working as intended". I _could_ try to filter out variables named `T`, but not sure if this is a safe way to handle this. Hence, I would indeed recommend generally using `TRUE` instead of `T`.

**Comment by wsbrum** [comment] 2020-12-15 14:17
Your package is amazing, probably not worth to try to come with a workaround for something peripheral and out of reach as this. Probably recommending using `TRUE` in the documentation would do the trick for less aware users like me. Thanks!!

**Comment by wsbrum** [comment] 2020-12-15 14:18
Your package is amazing, probably not worth to try to come with a workaround for something peripheral and out of reach as this. Probably recommending using TRUE in the documentation//setting a warning message (don't know how feasible it is) would do the trick for less skilled users like me. Thanks!!
