### ISSUE TITLE
Table to word with variables

### ISSUE THREAD

**Issue by jjp27** [strengejacke/sjPlot#337] opened 2018-03-06 09:34 UTC
Hi there,

I am trying to print a frequency table to Microsoft Word using sjPlot.

When I use print(freqsums), I get the table with a column describing the data (in my case the country name). However, when using sjPlot::tab_df(freqsums) I am not getting the column that shows the country name. Could you possibly tell me how to show the country name in the first column and not only the corresponding frequencies?

Best

**Comment by strengejacke** [comment] 2018-03-06 14:28
I have no idea what `freqsums` is. Do you have a reproducible example?

**Comment by jjp27** [comment] 2018-03-07 13:12
Sorry for being unclear. Basically I have a dataset that includes company data and one of the columns includes the companies' country.

In a first step I would like to show a table that shows the frequencies of countries (i.e. how many companies from each country in the dataset). I have reduced the dataset to a data table that has a column with the country names and the number of observations. When trying to plot this table with sjplot I am receiving a table that only includes the number of observations but not the corresponding country names.

Alternatively, is there a way to pull such a table directly from the underlying dataset?

**Comment by strengejacke** [comment] 2018-03-07 14:02
If I have a data frame with two columns, everything is correctly shown:

```
data(iris)
library(dplyr)
library(sjPlot)
iris %>% group_by(Species) %>% summarise(counts = n()) %>% tab_df()
```

I'm still not sure what is not working correctly. Perhaps it's helpful to post a minimal reproducible example, and probably the desired output?

**Comment by strengejacke** [comment] 2018-03-27 17:44
Any news on this issue?

**Comment by strengejacke** [comment] 2018-07-06 09:06
_(bump)_

**Comment by strengejacke** [comment] 2018-07-25 16:24
I'll close this issue for now, but feel free to reopen if you still encounter any problems.

**Closed by strengejacke** 2018-07-25 16:24 UTC
Labels: awaiting response

**Comment by iago-pssjd** [comment] 2019-12-16 15:28
Hi Daniel.
I arrived to this issue since I found the same fact. If I try your example
```
data(iris)
library(dplyr)
library(sjPlot)
iris %>% group_by(Species) %>% summarise(counts = n()) %>% tab_df()
```
what I get is
![sjplot](https://user-images.githubusercontent.com/40892925/70919155-a0f9f700-2020-11ea-9008-a74d9a04a612.png)
So, the level numbers of the factor variable `Species` instead of the actual names/labels of the levels.
