### ISSUE TITLE
error tab_model on lmerModMerTest

### ISSUE THREAD

**Issue by ScarlettKobs** [strengejacke/sjPlot#446] opened 2018-12-17 08:23 UTC
Hi,
I am trying to get a nice HTML Table from the mixed model I put up. Unfortunately, the tab_model-function does not seem to work. I want to compute p-values based on the Kenward-Rogers approximation. I get the following error message: 
*Error in round(attr(pv, "df.kr", exact = TRUE)) :* 
  *non-numeric argument to mathematical function* 
My model: 
    m7 <- lmer(GB ~  konstr.gerecht*dim + sexk+sexl+spFb+diag+sexk:sexl+sexk:spFb+spFb:diag+
                           (1 + kg2_1 + kg3_2 | subj), data=data, REML=FALSE)

It works when I use the p.val = "wald" attribute. I am not sure why. What can I do to solve this problem? 

Thanks in advance!
Scarlett

**Comment by ScarlettKobs** [comment] 2018-12-17 08:49
I found out what I was doing wrong. I didn't have the pbkrtest-package installed. It's working now.

**Comment by froemero** [comment] 2019-08-08 21:25
Hi Daniel,

I love your package! I'm using tab_model to make tables for my LMM outputs. So far so good, only that I now need to add df's due to a reviewer request. So when I change the way I call tab_model and set p.val = "kr" and show.df=TRUE, instead of getting my dfs in the table, I don't get no table at all and instead I get the same error message as above: "Error in round(attr(pv, "df.kr", exact = TRUE)): 
  non-numeric argument to mathematical function". I do have pbkrtest installed and I have also googled that error. Apparently that can happen if a data frame is fed into a function that wants a numerical input. Am I missing something? Is there a way to fix this? I could really use that functionality. :) 

Thanks and cheers,

Romy

**Comment by strengejacke** [comment] 2019-08-08 23:00
Do you have a reproducible example? This one works for me:

``` r
m <- insight::download_model("lmerMod_2")
sjPlot::tab_model(m, p.val = "kr", show.df = T)
```

<table style="border-collapse:collapse; border:none;">

<tr>

<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">

 

</th>

<th colspan="4" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">

wt

</th>

</tr>

<tr>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">

Predictors

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

Estimates

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

CI

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

p

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

df

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

(Intercept)

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

3.32

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.06 – 6.59

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.059

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

22.00

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

drat

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-0.58

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-1.34 – 0.17

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.160

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

10.00

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

cyl

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.32

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.13 – 0.50

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>0.002</strong>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

27.00

</td>

</tr>

<tr>

<td colspan="5" style="font-weight:bold; text-align:left; padding-top:.8em;">

Random Effects

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

s<sup>2</sup>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">

0.33

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

t<sub>00</sub> <sub>gear</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">

0.03

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

ICC

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">

0.08

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

N <sub>gear</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">

3

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">

Observations

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="4">

32

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

Marginal R<sup>2</sup> / Conditional R<sup>2</sup>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">

0.651 / 0.678

</td>

</tr>

</table>

<sup>Created on 2019-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by froemero** [comment] 2019-08-09 13:15
Deal Daniel, thanks for the quick reply. 
I ran your example and that worked. Weird!
Here's my model output. Does it work with that for you?
https://drive.google.com/file/d/1pwblHGxuPB_futt0qMY47smEepC5TnKB/view

**Comment by froemero** [comment] 2019-08-09 15:12
Update: I refit the model after detaching lmerTest and that worked!

**Comment by bbolker** [comment] 2019-08-09 15:42
reproducible example:

```
library(lmerTest)
fm3 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy,
            REML=TRUE)
sjPlot::tab_model(fm3,p.val="kr")
## Error in round(attr(pv, "df.kr", exact = TRUE)) : 
## non-numeric argument to mathematical function
```

**Comment by strengejacke** [comment] 2019-08-09 17:10
Thanks, should be fixed now! It seems that the pbkrtest-package does not return df for models of class `lmerModLmerTest` .

**Closed** 2019-08-09 17:09 UTC

**Comment by strengejacke** [comment] 2019-08-09 18:23
Note that returned p-values are probably based on Satterthwaite, not KR approximated df's. I openend an issue here: https://github.com/strengejacke/sjPlot/issues/530

**Comment by ferguskieran** [comment] 2021-07-01 03:58
Hi, I am having trouble using tab_model function.
I am receiving the follow error message;
Error in dat$p.value[dat$p.sig] <- sprintf("<strong>%s</strong>", dat$p.value[dat$p.sig]) : 
  NAs are not allowed in subscripted assignments
Any help would be greatly appreciated.

**Comment by bbolker** [comment] 2021-07-01 14:22
@ferguskieran, you should probably open a new issue, and you should definitely post a minimal reproducible example (see e.g. http://tinyurl.com/reproducible-000); there will be no way to help unless we can try an example that causes the same error.
