### ISSUE TITLE
Problem with adding polynomials

### ISSUE THREAD

**Issue by Marven82** [strengejacke/sjPlot#375] opened 2018-06-16 18:55 UTC
Hi!

I'm trying to visualize a logistic mixed effects model with the following variables:

dat.glmer <- glmer(dep_var~(numericvar1+factor1+numericvar2+I(numericvar2^2)+numericvar1*numericvar2+(1+numericvar1+factor1|listener),family= "binomial", control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)), data=data)

This model yields the following results:

Fixed effects:
                              Estimate Std. Error z value Pr(>|z|)    
(Intercept)                   -1.02664    0.22330  -4.598 4.27e-06 ***
numerivar1                1.26763    0.08562  14.805  < 2e-16 ***
factor1level1                    1.24183    0.23939   5.187 2.13e-07 ***
factor1level2                    1.84817    0.22863   8.084 6.28e-16 ***
numericvar2                  0.16322    0.05740   2.843  0.00446 ** 
I(numericvar2^2)            -0.58463    0.06574  -8.893  < 2e-16 ***
numericvar1:numericvar2 -0.31501    0.07654  -4.116 3.86e-05 ***

I tried to visualize this model in two ways:

plot_model(data_d_tone.glmer, type = "pred", terms = c("step_difference", "syllable"))

sjp.lm(data_d_tone, type = "poly", poly.term = "point_graphic")

The second failed completely; the first resulted in a picture that does not capture the complete model at all (see attachment for numericvar2 on the horizontal axis). Could you please tell me how to fix this issue? In other words, how can I capture the full model? Thanks in advance!

Marco

![predictedprobs](https://user-images.githubusercontent.com/40322851/41501564-58fa0f68-71a7-11e8-8757-e5dcd3d2a36c.png)

**Comment by strengejacke** [comment] 2018-06-16 20:14
I am a bit confused, because your variable names in the function call do not match those you used to fit the model.

What kind of plot would you like to get? The plot seems to be correct, as you are plotting predicted values for one variable against the response grouped by specific values of another variable.

**Comment by Marven82** [comment] 2018-06-17 05:41
My apologies for the confusion. The formulas should read:

plot_model(data.glmer, type = "pred", terms = c("numericvar2", "factor1"))

sjp.lm(data.glmer, type = "poly", poly.term = "numericvar2")

Strangely enough, the graph suggests a negative linear combined with a negative quadratic effect of numericvar2 ..., whereas my model should predict a positive linear combined with a negative quadratic effect, if you see what I mean (see model summary). Thanks again for your help!

**Comment by strengejacke** [comment] 2018-06-17 07:53
You have an interaction term in a logistic regression model, I think coefficients are not that straightforward to interpret in this case. You could cross check the results with the **effects** package, but I think the plot is correct. Without a reproducible example, however, I can't check.

**Comment by Marven82** [comment] 2018-06-18 09:13
I have attached a data file that contains all relevant variables. Here's my syntax:

temp <- read.table("data.txt", T)
temp$dep_var = as.factor(temp$dep_var)
temp$dep_var = relevel(temp$dep_var, ref = "T")
temp$listener = as.factor(temp$listener)
temp$factor1 = as.factor(temp$factor1)
temp$numericvar1 = as.numeric(temp$numericvar1)
temp$numericvar2 = as.numeric(temp$numericvar2)

data.glmer <- glmer(dep_var~(numericvar1+factor1+numericvar2+I(numericvar2^2))+(1+numericvar1+factor1|listener),family= "binomial", control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)), data=temp)

summary(data.glmer)

# Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
#  Family: binomial  ( logit )
# Formula: dep_var ~ (numericvar1 + factor1 + numericvar2 + I(numericvar2^2)) +      (1 + numericvar1 + factor1 | listener)
#    Data: temp
# Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e+05))
# 
#      AIC      BIC   logLik deviance df.resid 
#   2873.0   2968.5  -1420.5   2841.0     2864 
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -4.5355 -0.5594 -0.2033  0.5546  6.0716 
# 
# Random effects:
#  Groups   Name        Variance Std.Dev. Corr             
#  listener (Intercept) 1.3431   1.1589                    
#           numericvar1 0.1123   0.3351    0.51            
#           factor1l    1.4664   1.2109   -0.76 -0.68      
#           factor1m    1.2100   1.1000   -0.82 -0.32  0.80
# Number of obs: 2880, groups:  listener, 40
# 
# Fixed effects:
#                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)      -1.05397    0.22122  -4.764 1.89e-06 ***
# numericvar1       1.35578    0.08209  16.516  < 2e-16 ***
# factor1l          1.23034    0.23710   5.189 2.11e-07 ***
# factor1m          1.83486    0.22678   8.091 5.93e-16 ***
# numericvar2       0.21245    0.05504   3.860 0.000114 ***
# I(numericvar2^2) -0.43426    0.05426  -8.003 1.21e-15 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#             (Intr) nmrcv1 fctr1l fctr1m nmrcv2
# numericvar1  0.180                            
# factor1l    -0.762 -0.280                     
# factor1m    -0.788 -0.033  0.754              
# numericvar2  0.021  0.254  0.022  0.032       
# I(nmrcv2^2) -0.186  0.030 -0.028 -0.046 -0.156

Plot 1: plot_model(data.glmer, type = "pred", terms = c("numericvar2", "numericvar1"))
Plot 2: plot_model(data.glmer, type = "pred", terms = c("numericvar2"))

I am trying to create a plot that visualizes the effects of numericvar2 and the quadratic term I(numericvar2^2) on dep_var. Preferably, I would also like to include numericvar1 in the graph, as shown in the first plot_model example. To my understanding, the Plot 2 should result in a single line (which it does) that collapses the four lines in Plot 1. However, when I compare the two, the Plot 2 shows a single line that only has an average of approximately 20%, whereas the average of the four lines in the Plot 1 is much higher. Further, I don't really understand why the lines show such steady declines towards the right of Plot 1, especially for higher values of numericvar1, given the fact that I did not include an interaction between numericvar1 and numericvar2 in the model... In fact, when I look at the raw data (not included), the values at the right end of the graph are actually slightly higher than those at the left end of the graph..., which, as far as I can see, is also what the model summary suggests. I hope this elaboration is clear. If you need any further information, please let me know (I could send you the raw data via e-mail, if this helps). Thanks again for your help!

[data.txt](https://github.com/strengejacke/sjPlot/files/2110616/data.txt)

**Comment by strengejacke** [comment] 2018-06-18 13:39
Ok, while adressing this issue (which is actually an issue of the [ggeffects-package](https://github.com/strengejacke/ggeffects), as `plot_model()` simply calls `ggeffects::ggpredict()`, I added some additional features to that package which I will commit tonight.

According to your question, it indeed seems that the plots are allright. I have prepared a comparison with the [effects-package](https://cran.r-project.org/package=effects), which, however, deals differently when holding factors constant. That's why I have added the argument `condition = c(factor1 = "l")` below.

Here are the plots:

```r
effect("numericvar2", data.glmer) %>% plot()
![p1](https://user-images.githubusercontent.com/26301769/41539196-70d8f7a4-730d-11e8-8f36-5dbf4633dc13.png)

ggpredict(data.glmer, terms = "numericvar2 [range]", condition = c(factor1 = "l")) %>% plot()
![p2](https://user-images.githubusercontent.com/26301769/41539202-74752d42-730d-11e8-9db5-5adcf195a908.png)

# Taking random effects variance for prediction intervals into account
ggpredict(data.glmer, terms = "numericvar2 [range]", condition = c(factor1 = "l"), type = "re") %>% 
  plot(log.y = TRUE, breaks = c(.01, .05, .1, .15, .2, .3, .5, .8))
![p3](https://user-images.githubusercontent.com/26301769/41539205-76c94484-730d-11e8-8a46-87e6ab8a5af6.png)

Effect(c("numericvar2", "numericvar1"), data.glmer) %>% plot()
![p4](https://user-images.githubusercontent.com/26301769/41539249-934d7116-730d-11e8-9b4f-8b93d02a7a45.png)

ggpredict(data.glmer, terms = c("numericvar2 [range]", "numericvar1 [-1, -.4, .3, .9, 2]"), condition = c(factor1 = "l")) %>% plot(facets = T)
![p5](https://user-images.githubusercontent.com/26301769/41539256-9842f81c-730d-11e8-8684-dfaa3e9d548b.png)

# no facets
ggpredict(data.glmer, terms = c("numericvar2 [range]", "numericvar1 [-1, -.4, .3, .9, 2]"), condition = c(factor1 = "l")) %>% plot()
![p6](https://user-images.githubusercontent.com/26301769/41539281-aaa00374-730d-11e8-813a-057c251bd2c2.png)
```

As you can see, I chose the same values for `numericvar1` as the **effects**-package does by default, to get comparable plots. I don't see any problems here, or am I missing something?

**Comment by Marven82** [comment] 2018-06-18 19:10
Thank you very much for sorting this out. I'm glad to see that the new plots (the last one) now hardly shows a negative decline, as I expected. Further, I'm glad that it is possible to also integrate variances of the random effects in the plots. I guess I will need to update the packages, after you've added these functions this evening? Thanks, again!

Cheers,

Marco

**Comment by strengejacke** [comment] 2018-06-18 20:39
Yes, it's all committed to github,so basically, you need to update **ggeffects** and that should do it, I think.

**Closed by strengejacke** 2018-06-18 20:39 UTC
