### ISSUE TITLE
Error using plot_model 

### ISSUE THREAD

**Issue by adriana000** [strengejacke/sjPlot#388] opened 2018-07-21 14:44 UTC
I am trying to use plot_model function without success...

For example, when I type this:

`m1 <- lmer(distance ~ age + Sex + (1 | Subject), data = Orthodont)` 

This error appears:

` Error:  Column 6 must be named` 

Thank you

**Comment by strengejacke** [comment] 2018-07-21 17:43
Are all packages up to date?

**Comment by adriana000** [comment] 2018-07-21 22:18
Yes.
Today I updated sjPlot, lme4, lmerTest, nlme, Matrix...
R version is R-3.4.4

**Comment by strengejacke** [comment] 2018-07-23 07:47
I can't reproduce this error. Can you post your session info?

**Comment by RandomSubject** [comment] 2018-07-25 09:47
I also got this error when using lme4 in combination with lmerTest and building a results table with  function `tab_model()`. After unloading package lmerTest and running my mixed model again, `tab_model()` was build like a charm. Same error occured for packages cowplot and stargazer when using lme4 combined with lmerTest.

Minimal example:
```
require(lme4)
require(nlme) # using Orthodont data
require(lmerTest)
require(sjPlot)
m1 <- lmer(distance ~ age + Sex + (1 | Subject), data=Orthodont); summary(m1)
tab_model(m1) # Error: Column 6 must be named
unloadNamespace("lmerTest")
# re-run mixed model without lmerTest
m1 <- lmer(distance ~ age + Sex + (1 | Subject), data=Orthodont); summary(m1)
tab_model(m1) # results table built
```

My session info (this error also appeared on macOS High Sierra 10.13.6)
```
sessionInfo()
```
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
> [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] lmerTest_3.0-1 bindrcpp_0.2.2 sjPlot_2.5.0   nlme_3.1-137   lme4_1.1-17    Matrix_1.2-14 
> 
> loaded via a namespace (and not attached):
>  [1] tidyr_0.8.1        splines_3.5.1      carData_3.0-1      modelr_0.1.2       assertthat_0.2.0   stats4_3.5.1      
>  [7] coin_1.2-2         numDeriv_2016.8-1  pillar_1.3.0       backports_1.1.2    lattice_0.20-35    glue_1.3.0        
> [13] glmmTMB_0.2.2.0    snakecase_0.9.1    minqa_1.2.4        colorspace_1.3-2   sandwich_2.4-0     psych_1.8.4       
> [19] survey_3.33-2      plyr_1.8.4         pkgconfig_2.0.1    broom_0.5.0        haven_1.1.2        purrr_0.2.5       
> [25] xtable_1.8-2       mvtnorm_1.0-8      scales_0.5.0       stringdist_0.9.5.1 emmeans_1.2.3      arm_1.10-1        
> [31] tibble_1.4.2       effects_4.0-2      bayesplot_1.5.0    ggplot2_3.0.0      sjlabelled_1.0.12  TH.data_1.0-9     
> [37] nnet_7.3-12        TMB_1.7.14         lazyeval_0.2.1     mnormt_1.5-5       survival_2.42-3    magrittr_1.5      
> [43] crayon_1.3.4       estimability_1.3   MASS_7.3-50        foreign_0.8-70     forcats_0.3.0      tools_3.5.1       
> [49] data.table_1.11.4  hms_0.4.2          multcomp_1.4-8     stringr_1.3.1      munsell_0.5.0      prediction_0.3.6  
> [55] ggeffects_0.4.0    compiler_3.5.1     rlang_0.2.1        grid_3.5.1         nloptr_1.0.4       ggridges_0.5.0    
> [61] gtable_0.2.0       codetools_0.2-15   abind_1.4-5        sjstats_0.16.0     sjmisc_2.7.3       R6_2.2.2          
> [67] zoo_1.8-3          knitr_1.20         pwr_1.2-2          dplyr_0.7.6        bindr_0.1.1        modeltools_0.2-22 
> [73] stringi_1.1.7      parallel_3.5.1     Rcpp_0.12.17       tidyselect_0.2.4   coda_0.19-1        lmtest_0.9-36    


Cheers!

**Comment by strengejacke** [comment] 2018-07-25 16:19
Ok, the solution is: please use _lme4_ to fit the model, not _lmerTest_. There's a bug in broom, and once this bug is fixed resp. if the package _broom.mixed_ is released, this bug should be fixed.

**Closed by strengejacke** 2018-07-25 16:19 UTC
Labels: awaiting response

**Comment by adriana000** [comment] 2018-07-28 20:30
Thanks!

**Comment by strengejacke** [comment] 2018-08-02 10:00
I added a workaround (i.e. an own tidier) for lmerModLmerTest-Objects, so this issue should be fixed in sjPlot now. Will commit tonight.

**Comment by GingerJoey** [comment] 2018-09-09 11:27
When I try to plot the interaction of a random effects model from the plm package I receive a similar error: 

plot_model(Random.5, type = "int", mdrt.values = c("meansd"))
Error: Columns 6, 7 must be named

Is this related?

**Comment by strengejacke** [comment] 2018-09-09 16:40
I don't think so. I remember there were some oddities with plm-random-effects-models, that's why these are not properly supported. But I can look into this issue, do you have a reproducible example? Please also open a new issue, so I can keep track of this issue.
