### ISSUE TITLE
tab_model and sjt.glmer not working with glmer

### ISSUE THREAD

**Issue by nkcaselli** [strengejacke/sjPlot#400] opened 2018-08-15 13:31 UTC
I had a glmer model that was working just fine with tab_model and sjt.glmer two days ago, but is now throwing this error for tab_model

> Error in UseMethod("family") : 
>   no applicable method for 'family' applied to an object of class "character"

and this error for sjt.glmer

> Error in mutate_impl(.data, dots) : 
>   Evaluation error: 'names' attribute [5] must be the same length as the vector [2].

The model is:

```
model1 <-glmer(Error ~  Age + ASLAge  + EnglishExposure + ASLExposure + SignOnset + SignOffset + TrialNum+preverror + logprevRT + MajorLocationFrequency*SignFrequency.Z.+HandshapeFrequency*SignFrequency.Z.  + Iconicity.Z.*SignFrequency.Z.  + (1|EntryID)+(1 + MajorLocationFrequency + HandshapeFrequency + SignFrequency.Z. +Iconicity.Z.|Participant), family = binomial, data = AccuracyDoDOnly, nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))

sjt.glmer(model1 ,file = "~/Desktop/test.html")
tab_model(model1 ,file = "~/Desktop/test.html")

```
Any ideas?

**Comment by strengejacke** [comment] 2018-08-15 14:07
Yes, the `file`-argument is not implemented in the current version on CRAN, but will be in the forthcoming update. That's why currently the `file`-argument is considered as model-object (because it's captured by the `...`).

You can either wait for the _sjPlot_-update on CRAN, or you install _sjstats_ and _sjPlot_ from Github, then the code should work.

**Comment by nkcaselli** [comment] 2018-08-15 14:25
Thanks for your help. I am still having trouble with the Github versions. When will the update be on CRAN?

**Comment by strengejacke** [comment] 2018-08-15 16:59
Strange. Do you have a reproducible example? Or data?

**Comment by nkcaselli** [comment] 2018-08-15 17:31
Scratch that. I think I fixed it, though I am not sure how.

**Comment by strengejacke** [comment] 2018-08-15 18:07
miRacle 😉

**Closed** 2018-08-15 21:04 UTC

**Comment by benjaminwnelson** [comment] 2019-03-20 22:00
I am getting that same error and I am not using a file path. Any ideas?

**Comment by strengejacke** [comment] 2019-03-20 22:21
What do you exactly mean by "name the variables"?

**Comment by benjaminwnelson** [comment] 2019-03-21 18:06
I am able to print a table of results, but when I try to change the names of the variables in the table I get the error `Error in UseMethod("family") : no applicable method for 'family' applied to an object of class "character"`

**Comment by strengejacke** [comment] 2019-03-21 19:43
If that error message occurs, most likely an argument is misspelled.
