### ISSUE TITLE
plot_xtab mislabelling factor levels, v. 2.8.3

### ISSUE THREAD

**Issue by Westendline** [strengejacke/sjPlot#628] opened 2020-04-15 18:35 UTC
Please see the link to an issue I posed in stackoverflow:

https://stackoverflow.com/questions/61219021/problem-with-sjplotplot-xtab-mislabelling-factor-levels/61220198#61220198

This bug is not occurring in v. 2.8.0

**Comment by strengejacke** [comment] 2020-04-16 11:47
possible duplicate of #616, should be fixed already.

**Closed by strengejacke** 2020-04-16 11:47 UTC
