### ISSUE TITLE
Suggestions for plot_model labels

### ISSUE THREAD

**Issue by cschwem2er** [strengejacke/sjPlot#299] opened 2017-11-18 11:13 UTC
Hi, 
when using `plot_model`() with `type = 'std2'` I get an error, while `std` and `est` work just fine:
```
library(sjPlot)
library(tidyverse)

reg_sent <- glm(sentiment ~  . , data = df_reg)
sjt.glm(reg_sent, show.ci = F, p.numeric = F,
       show.se = T, exp.coef = F,
      depvar.labels =  c('Model 1'))
summary(reg_sent)

plot_model(reg_sent)
```

![image](https://user-images.githubusercontent.com/7460499/32979617-f20d8616-cc58-11e7-9b2c-48386943de7a.png)

```
plot_model(reg_sent, type = 'std2')


Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 2333, 0
20.
stop(gettextf("arguments imply differing number of rows: %s", paste(unique(nrows), collapse = ", ")), domain = NA)
19.
data.frame(..., check.names = FALSE)
18.
cbind(deparse.level, ...)
17.
cbind(get(as.character(call$data)), newvars)
16.
assign(as.character(call$data), cbind(get(as.character(call$data)), newvars))
15.
standardize.default(call = call, unchanged = unchanged, standardize.y = standardize.y, binary.inputs = binary.inputs)
14.
.local(object, ...)
13.
arm::standardize(fit)
12.
arm::standardize(fit)
11.
stats::coef(arm::standardize(fit))
10.
sjstats::std_beta(., type = type, ci.lvl = ci.lvl)
9.
function_list[[i]](value)
8.
freduce(value, `_function_list`)
7.
`_fseq`(`_lhs`)
6.
eval(quote(`_fseq`(`_lhs`)), env, env)
5.
eval(quote(`_fseq`(`_lhs`)), env, env)
4.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3.
model %>% sjstats::std_beta(type = type, ci.lvl = ci.lvl) %>% tibble::add_column(p.value = sjstats::p_value(model)[["p.value"]][-1]) %>% sjmisc::var_rename(std.estimate = "estimate")
2.
plot_type_est(type = type, ci.lvl = ci.lvl, tf = transform, model = model, terms = terms, group.terms = group.terms, rm.terms = rm.terms, sort.est = sort.est, title = title, axis.title = axis.title, axis.labels = axis.labels, axis.lim = axis.lim, grid.breaks = grid.breaks, ...
1.
plot_model(reg_sent, type = "std2")


```
If you need my data to reproduce the example, please find it [here](https://www.dropbox.com/s/rl0nv5l8m7cr4q2/ted_reg_std2.RData?dl=1).

You only standardize the continuous variables there and leave dummies and factors as is right? Because the documentation only states
> rescaling the estimates by dividing them by two standard deviations instead of just one.
without any exceptions.

In addition, the standard output from `plot_model()` already looks pretty nice but I'd like to suggest two minor improvements (see output above):
- Include a regex that checks for variables which include white spaces or other non-conventional characters and are therefore surrounded with \` and remove the \` characters. I think it's bad practice to assign column name like that, but sometimes it is necessary, especially for automating some stuff.
- For factor variables, apply a solution similar to the output from `sjt.glm()`: either include the displayed category in brackets, e.g.  "ethnicity (non-white)", or maybe with a ":", e.g. "ethnicity: non-white".
- (if possible): add an option to include [rugplots](http://ggplot2.tidyverse.org/reference/geom_rug.html) for predict values. They are super useful to show for which plot areas only limited observations are included in the underlying data. Unfortunately this does not work: 
`plot_model(reg_sent, type = 'pred', terms = 'date') + geom_rug()` as there is no information about the number of observations available in the `plot_model` object.

**Comment by strengejacke** [comment] 2017-11-18 13:43
Regarding your initial query: this seems to be an issue with `arm::standardize()`. I'm not sure, the traceback is not very helpful in this case...

1) According your first suggestion, names: Try to play around with the `case`-argument. By default, labels are processed by the *snakecase*-package. Maybe @Tazinho can help further?

2) This might be possible, I must see if I can directly include an option in `sjlabelled::get_term_labels()` - there's already an `mark.cat`-argument, which might be enhanced to combine variable and value labels for categorical variables.

3) For predictions, use *ggeffects*, which returns the raw data as attribute. You just have to build the ggplot-plot by yourself:

```
m <- glm(sentiment ~  . , data = df_reg)
dat <- ggpredict(m, terms = "date")
ggplot(dat, aes(x = x, y = predicted)) + 
  geom_line() +
  geom_rug(data = attr(dat, "rawdata"), aes(x = x, y = response))
```

**Comment by strengejacke** [comment] 2017-11-18 13:47
@Tazinho - see here for my case processing with scnakecase in *sjlabelled*:
https://github.com/strengejacke/sjlabelled/blob/1e081f789afaffcd56ede0f6e7de98b08bd91d04/R/helpfunctions.R#L174

**Comment by Tazinho** [comment] 2017-11-19 15:04
@methodds and @sjPlot regarding the naming conventions. It's relatively easy, to change names for
1. valid names for internal processing
2. nice looking names for plots

I am not sure, if I am getting your intentions correct, but if you need the names only internally, you could also use sth. like var1, var2, var3 etc. and build up a lookup to match var1, var2, var3 to the prettified names. If you don't like the idea and want to customize the names to a more robust output, you could also go the way below and remove i. e. all spaces and non alphanumeric characters:

```
> ##  ............................................................................
> #   some weird input names
> strange_names <- c("Var 1", "  var 1 @ bla", " var +.### 1", " some words ")
> #   ____________________________________________________________________________
> #   original convert_case function
> convert_case <- function(lab, case) {
+ if (!is.null(case) && !is.null(lab)) {
+ snakecase::to_any_case(
+ lab,
+ case = case,
+ preprocess = "(?<!\\d)\\.",
+ postprocess = " ",
+ protect = "\\d"
+ )
+ } else {
+ lab
+ }
+ }
> ### . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ..
> #   customized convert_case function:
> #   basically, we change
> #   - preprocess to convert every non-alphanumeric sign into underscore
> #   - postprocess to separate different words with "_" or "" (regarding the case),
> #     but not " " anymore
> convert_case2 <- function(lab, case) {
+ if (!is.null(case) && !is.null(lab)) {
+ snakecase::to_any_case(
+ lab,
+ case = case,
+ preprocess = "[^[:alnum:]]",
+ protect = "\\d"
+ )
+ } else {
+ lab
+ }
+ }
> #   ____________________________________________________________________________
> #   Compare results
> convert_case(strange_names,
+ case = "parsed")
[1] "Var1"         "var1@ bla"    "var + # # #1" "some words"  
> convert_case2(strange_names,
+ case = "parsed")
[1] "Var1"       "var1bla"    "var1"       "some_words"
```

If you want to move on with this issue, let me know if I can help and maybe provide me a reproducible example with clear expectations, how the output should look like.

**Comment by strengejacke** [comment] 2017-11-19 17:23
I think only accepting alpha numeric would be too much. I think chars like & or + or - should be kept as well.
But if I get this right, you could remove unwanted leading and trailing chars via the regex in the`preprocess` argument?

**Comment by strengejacke** [comment] 2017-11-19 17:25
Or maybe I should either allow some "pre-defined" values for the preprocess argument, or even allow user defined preprocess values passed down to the case convert function.

**Comment by strengejacke** [comment] 2017-11-19 21:48
hm, `postprocess = NULL` gives an error for me. Are you using the CRAN or GitHub-version of *snakecase*?

**Comment by strengejacke** [comment] 2017-11-19 21:57
Ok, after installing the latest _sjlabelled_ and _sjPlot_ from GitHub, you can use `preprocess`, `postprocess` and `protect` in `plot_model()`. We may consider other defaults to improve the automatic case conversion for term labels... Suggestions?

@Tazinho 
> if I can help and maybe provide me a reproducible example with clear expectations, how the output should look like.
See initial post, the figure. Term labels stem from column names and are surrounded by tick marks. These should be removed... I believe, it's possible with regex. But regex are my enemies...

**Comment by strengejacke** [comment] 2017-11-19 22:21
@methodds I think your initial query is something I can't fix, as it is related to the arm-package. Please change this issue's title accordingly to the current label discussion.

**Comment by methodds** [comment] 2017-11-19 22:51
okay, thanks for trying anyway. Are you still gonna keep the potentially bugged `std2` option?

**Comment by strengejacke** [comment] 2017-11-20 20:50
> Are you still gonna keep the potentially bugged std2 option?

Do you mean whether this option will remain as plot-type? Yes, I think so, as - at least in my case - always worked. I haven't looked into the data, so I'm not sure, what exactly is causing the error. Maybe you can open an issue at arm's GitHub-page, if you like to pursue this issue.

**Comment by Tazinho** [comment] 2017-11-21 08:04
I might not be able to look into this right now, but here is a smaller reproducible example, which shows behaviour for typical columns and messed up columns (`iris2`). So as mentioned by @methodds it might just be necessary to trim the backticks in the beginning of `convert_case()`.

``` r
library(sjPlot)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

mod_iris1 <- lm(Sepal.Width ~ ., data = iris)

plot_model(mod_iris1)
```

![](https://i.imgur.com/W052Z4W.png "fig:")

``` r

iris2 <- iris %>% rename("Species 2" = Species, "Sepal Length" = Sepal.Length )

mod_iris2 <- lm(Sepal.Width ~ ., data = iris2)

plot_model(mod_iris2)
```

![](https://i.imgur.com/Tex1Zxe.png "fig:")

**Comment by methodds** [comment] 2017-11-21 09:21
couldn't this then be something similar to this?

```
input_strings <- c('`bacon&eggs`', '`food & farming`', '`snake_case`')
  
# base r
  regmatches(input_strings, regexec('^`(.*)`$', input_strings)) 

[[1]]
[1] "`bacon&eggs`" "bacon&eggs"  

[[2]]
[1] "`food & farming`" "food & farming"  

[[3]]
[1] "`snake_case`" "snake_case"  

# string r
  library(stringr)
  str_match(input_strings, '^`(.*)`$')[, 2]

[1] "bacon&eggs"     "food & farming" "snake_case" 
  ```
or even simpler (just getting rid of every ` ` ` in the string:

```
str_replace_all(input_strings, '`', '')
[1] "bacon&eggs"     "food & farming" "snake_case"  
```

**Comment by Tazinho** [comment] 2017-11-21 10:01
Yep, or like this. I think it's better, but we should rerun the reprex with the plot to decide if it is necessary to remove all backticks.

``` r

library(stringr)

test <- c("`both`", 
          "`left",
          "right`",
          "mid ` dle",
          "``left_2")
test
#> [1] "`both`"    "`left"     "right`"    "mid ` dle" "``left_2"

str_replace_all(test, "^`+|`+$", "")
#> [1] "both"      "left"      "right"     "mid ` dle" "left_2"
```

**Comment by strengejacke** [comment] 2017-11-21 10:12
@methodds could you try the latest dev-versions, including latest of sjlabelled? You should be able to pass this regex as `preprocess`-argument to `plot_model()`.

My question is:

1. is this enough?
2. should the regex be changes in `convert_case()`, for reasons of user-friendlyness?

**Comment by methodds** [comment] 2017-11-21 10:36
Yep, I just downloaded the latest versions for sjPlot and sjlabelled but I',m not sure whether it is working properly: 
`` plot_model(mod_iris2, preprocess = '^`+|`+$') `` 
![image](https://user-images.githubusercontent.com/7460499/33067756-759792da-ceaf-11e7-917c-74d85d6c8de2.png)
The first ``  `  `` for the `virginica` category remains. If I try the simple regex to remove all ``  `  `` it looks like this:
`` plot_model(mod_iris2, preprocess = '`') `` 
![image](https://user-images.githubusercontent.com/7460499/33067828-afc9065a-ceaf-11e7-85b5-1e8ff8559dd5.png)

This seems to be inconsistent for different categories of factor variables. Is this maybe something that should rather be done with `postprocess` ?

**Comment by strengejacke** [comment] 2017-11-21 10:38
or it might be triggered with `protect`. As I'm not familiar with regex, I can't help that much. You may look what `convert_case()` does by default (https://github.com/strengejacke/sjPlot/issues/299#issuecomment-345443418), and set the arguments `preprocess`, `postprocess` and `protect` accordingly.

Maybe one solution is indeed to simply remove leading/trailing tickmarks and backticks.

**Comment by Tazinho** [comment] 2017-11-21 10:55
No, `postprocess` only converts the spaces between words (internally underscores before) into the final form.

**Comment by Tazinho** [comment] 2017-11-21 11:06
I guess `convert_case` works well. At least the snakecase output for the terms looks ok (see the code example). I am not sure, since I am not so deep into the `plot_model()` code, but the labelling issue could also be within ggplot2!?

``` r
library(sjPlot)
library(tidyverse)

iris2 <- iris %>% rename("Species 2" = Species, "Sepal Length" = Sepal.Length )

mod_iris2 <- lm(Sepal.Width ~ ., data = iris2)
terms <- broom::tidy(mod_iris2) %>% pull(term) 

terms
#> [1] "(Intercept)"           "`Sepal Length`"        "Petal.Length"         
#> [4] "Petal.Width"           "`Species 2`versicolor" "`Species 2`virginica"
terms %>%
  snakecase::to_any_case(preprocess = "`", postprocess = " ")
#> [1] "( intercept )"        "sepal length"         "petal . length"      
#> [4] "petal . width"        "species 2 versicolor" "species 2 virginica"
```

**Comment by strengejacke** [comment] 2017-11-21 11:50
Inside `plot_model()`, following named vector is returned:

```
Browse[2]> axis.labels
       `Sepal Length`          Petal.Length           Petal.Width `Species 2`versicolor 
       "Sepal Length"      "Petal . Length"       "Petal . Width"  "Species2versicolor" 
           Species 21            Species 22            Species 23 
             "setosa"          "versicolor"           "virginica" 
```

When settings axis-labels in ggplot, using `scale_x_discret()`, factor levels and vector names still match:

```
Browse[4]> names(axis.labels)
[1] "`Sepal Length`"        "Petal.Length"          "Petal.Width"           "`Species 2`versicolor"
[5] "Species 21"            "Species 22"            "Species 23"           
Browse[4]> levels(dat$term)
[1] "Petal.Width"           "Petal.Length"          "`Species 2`virginica"  "`Species 2`versicolor"
[5] "`Sepal Length`"       
Browse[4]> 
```

So, I assume this is a ggplot-issue when matching the names label-vector with factor-levels. If this is the case, then it would not help to internally remove backticks, but to rename columns to proper names.

**Comment by methodds** [comment] 2017-11-21 15:47
hmmm or one could just rely on variable labels. But I don't understand why the following is not working:
```
data(iris)
iris2 <- set_label(iris, 
                    label = c("Sepal!Length", "Sepal.Width",  "Petal.Length" ,
                               "Petal_Width" , "Sp€cies~2"))

mod_iris <- lm(Sepal.Width ~ ., data = iris2)
plot_model(mod_iris)
```
If working with variable labels, wouldn't the plot here supposed to be displaying the labels completely unchanged (and append the factor categories in a nice format)?

![image](https://user-images.githubusercontent.com/7460499/33081840-8dfd9f46-cedb-11e7-9f61-2bdf401d496a.png)

**Comment by strengejacke** [comment] 2017-11-21 16:58
The `labels` argument of the `ggplot::scale_*_discrete()` functions accepts named vectors. The values at the discrete axis are treated as factors, and by default the factor levels are used to annotate the axis. If you have a named vector, all value _names_ of this factor are matched against the factor levels, and in case of a match, replaced by the value (label).

This makes it easy to correctly assign labels without worrying the label order, in case you re-ordered the factor levels.

**Comment by strengejacke** [comment] 2017-11-21 17:03
`sjlabelled::get_term_labels()`, which is used by `plot_model()`, returns the value labels from model terms as named vector, where the names are the "factor levels" from `as.factor(broom::tidy(model)$term)`.

**Comment by strengejacke** [comment] 2017-11-21 17:04
This saves me a lot of work whether correctly assigning axis labels, no matter if labels are incomplete or in a completely different order (e.g. if terms are re-ordered or removed from the output).

**Comment by strengejacke** [comment] 2017-11-21 17:06
(because ggplot takes care of label matching when the labels-argument is a _named_ vector.

**Comment by strengejacke** [comment] 2017-11-21 18:00
> If working with variable labels, wouldn't the plot here supposed to be displaying the labels completely unchanged (and append the factor categories in a nice format)?

No, not if the variable is treated as continuous. Then, variable labels are displayed.

**Comment by strengejacke** [comment] 2018-01-12 18:26
What is the current state of this issue? Are there still unsolved things here?

**Comment by methodds** [comment] 2018-01-16 17:29
Hm I guess not, feel free to close it :>

**Comment by strengejacke** [comment] 2018-01-16 18:57
I just saw that this one is still open:

> For factor variables, apply a solution similar to the output from sjt.glm(): either include the displayed category in brackets, e.g. "ethnicity (non-white)", or maybe with a ":", e.g. "ethnicity: non-white".

**Comment by phisherblack** [comment] 2018-08-10 01:34
is there any progress on the "std2" issue?

**Comment by methodds** [comment] 2018-08-15 13:25
> is there any progress on the "std2" issue?
at least not from my end

**Comment by strengejacke** [comment] 2018-08-15 14:05
I have fixed some issues with `type = "std2"` - you may check after update _sjstats_ and _sjPlot_ from GitHub.

**Comment by cschwem2er** [comment] 2018-11-18 18:29
Sorry for responding so late, are these fixes now also included in the current CRAN version of sjPlot?

**Comment by strengejacke** [comment] 2018-11-18 19:13
Yes.

**Comment by strengejacke** [comment] 2018-11-22 11:04
> For factor variables, apply a solution similar to the output from sjt.glm(): either include the displayed category in brackets, e.g. "ethnicity (non-white)", or maybe with a ":", e.g. "ethnicity: non-white".

This one is now possible with `plot_model()` and `tab_model()`, by using the `prefix.labels`-argument.

I guess I can close this now?

**Closed by strengejacke** 2018-11-22 11:04 UTC
Labels: enhancement

**Comment by cschwem2er** [comment] 2018-11-22 11:18
yes, thanks :)
